// Single responsibility: subscribe to all Zustand stores and expose a unified canvas state snapshot.
import { useMemo, useEffect } from "react";
import { useShallow } from "zustand/react/shallow";
import { useCanvasStore } from "@/stores/canvas.store";
import { useMediaStore } from "@/stores/media.store";
import { useSceneStore } from "@/stores/scene.store";
import { useUiStore } from "@/stores/ui.store";

export function useCanvasState() {
  useEffect(() => {
    console.log("[useCanvasState] mounted");
  }, []);

  // --- Canvas Store ---
  const {
    layoutMode,
    setLayoutMode,
    cameraShape,
    setCameraShape,
    splitRatio,
    setSplitRatio,
    pipPosition,
    setPipPosition,
    pipSize,
    setPipSize,
    isTransitioning,
    activeTransition,
    dynamicLayout,
  } = useCanvasStore(
    useShallow((s) => ({
      layoutMode: s.layoutMode,
      setLayoutMode: s.setLayoutMode,
      cameraShape: s.cameraShape,
      setCameraShape: s.setCameraShape,
      splitRatio: s.splitRatio,
      setSplitRatio: s.setSplitRatio,
      pipPosition: s.pipPosition,
      setPipPosition: s.setPipPosition,
      pipSize: s.pipSize,
      setPipSize: s.setPipSize,
      isTransitioning: s.isTransitioning,
      activeTransition: s.activeTransition,
      dynamicLayout: s.dynamicLayout,
    })),
  );

  // --- Media Store ---
  const {
    isAudioOn,
    setAudioOn,
    isVideoOn,
    setVideoOn,
    audioDevices,
    selectedAudioDevice,
    setSelectedAudioDevice,
    videoDevices,
    selectedVideoDevice,
    setSelectedVideoDevice,
    selectedScreenSourceId,
    setSelectedScreenSourceId,
    screenShareMode,
    setScreenShareMode,
  } = useMediaStore(
    useShallow((s) => ({
      isAudioOn: s.isAudioOn,
      setAudioOn: s.setAudioOn,
      isVideoOn: s.isVideoOn,
      setVideoOn: s.setVideoOn,
      audioDevices: s.audioDevices,
      selectedAudioDevice: s.selectedAudioDevice,
      setSelectedAudioDevice: s.setSelectedAudioDevice,
      videoDevices: s.videoDevices,
      selectedVideoDevice: s.selectedVideoDevice,
      setSelectedVideoDevice: s.setSelectedVideoDevice,
      selectedScreenSourceId: s.selectedScreenSourceId,
      setSelectedScreenSourceId: s.setSelectedScreenSourceId,
      screenShareMode: s.screenShareMode,
      setScreenShareMode: s.setScreenShareMode,
    })),
  );

  // --- Scene Store ---
  const {
    customMaskUrl,
    setCustomMaskUrl,
    activeOverlays,
    setActiveOverlays,
    textOverlays,
    setTextOverlays,
    fileOverlays,
    setFileOverlays,
    browserOverlays,
    setBrowserOverlays,
    emptyGridPanels,
    setEmptyGridPanels,
    canvasLayout,
    setCanvasLayout,
    backgroundEffect,
    setBackgroundEffect,
    backgroundImageUrl,
    setBackgroundImageUrl,
    blankCanvasColor,
    setBlankCanvasColor,
    videoFilter,
    setVideoFilter,
    captionStyle,
    setCaptionStyle,
    dynamicStyle,
    setDynamicStyle,
    isAiModeEnabled,
    setAiModeEnabled,
    captionsEnabled,
    setCaptionsEnabled,
    previousScene,
    selectedBrowserId,
    setSelectedBrowserId,
    selectedFileId,
    setSelectedFileId,
    selectedTextId,
    setSelectedTextId,
    selectedGeneratedId,
    setSelectedGeneratedId,
    deselectAll,
    pipRotation,
    setPipRotation,
    pipBorder,
    setPipBorder,
    pipShadow,
    setPipShadow,
    cameraAspectRatio,
    setCameraAspectRatio,
    customAspectRatio,
    setCustomAspectRatio,
    activeInteractiveFilter,
    setActiveInteractiveFilter,
    filterIntensity,
    setFilterIntensity,
    filterColor,
    setFilterColor,
    filterTarget,
    setFilterTarget,
    isAutoFramingEnabled,
    setIsAutoFramingEnabled,
    isBeautifyEnabled,
    setIsBeautifyEnabled,
    isLowLightEnabled,
    setIsLowLightEnabled,
    isNeonEdgeEnabled,
    setIsNeonEdgeEnabled,
    neonIntensity,
    setNeonIntensity,
    neonColor,
    setNeonColor,
    cameraBackground,
    setCameraBackground,
    customBackgroundUrl,
    setCustomBackgroundUrl,
    zoomSensitivity,
    setZoomSensitivity,
    trackingSpeed,
    setTrackingSpeed,
    isFaceTrackingEnabled,
    setIsFaceTrackingEnabled,
    canvasAspectRatio,
    setCanvasAspectRatio,
  } = useSceneStore(
    useShallow((s) => ({
      customMaskUrl: s.customMaskUrl,
      setCustomMaskUrl: s.setCustomMaskUrl,
      activeOverlays: s.activeOverlays,
      setActiveOverlays: s.setActiveOverlays,
      textOverlays: s.textOverlays,
      setTextOverlays: s.setTextOverlays,
      fileOverlays: s.fileOverlays,
      setFileOverlays: s.setFileOverlays,
      browserOverlays: s.browserOverlays,
      setBrowserOverlays: s.setBrowserOverlays,
      emptyGridPanels: s.emptyGridPanels,
      setEmptyGridPanels: s.setEmptyGridPanels,
      canvasLayout: s.canvasLayout,
      setCanvasLayout: s.setCanvasLayout,
      backgroundEffect: s.backgroundEffect,
      setBackgroundEffect: s.setBackgroundEffect,
      backgroundImageUrl: s.backgroundImageUrl,
      setBackgroundImageUrl: s.setBackgroundImageUrl,
      blankCanvasColor: s.blankCanvasColor,
      setBlankCanvasColor: s.setBlankCanvasColor,
      videoFilter: s.videoFilter,
      setVideoFilter: s.setVideoFilter,
      captionStyle: s.captionStyle,
      setCaptionStyle: s.setCaptionStyle,
      dynamicStyle: s.dynamicStyle,
      setDynamicStyle: s.setDynamicStyle,
      isAiModeEnabled: s.isAiModeEnabled,
      setAiModeEnabled: s.setAiModeEnabled,
      captionsEnabled: s.captionsEnabled,
      setCaptionsEnabled: s.setCaptionsEnabled,
      previousScene: s.previousScene,
      selectedBrowserId: s.selectedBrowserId,
      setSelectedBrowserId: s.setSelectedBrowserId,
      selectedFileId: s.selectedFileId,
      setSelectedFileId: s.setSelectedFileId,
      selectedTextId: s.selectedTextId,
      setSelectedTextId: s.setSelectedTextId,
      selectedGeneratedId: s.selectedGeneratedId,
      setSelectedGeneratedId: s.setSelectedGeneratedId,
      deselectAll: s.deselectAll,
      pipRotation: s.pipRotation,
      setPipRotation: s.setPipRotation,
      pipBorder: s.pipBorder,
      setPipBorder: s.setPipBorder,
      pipShadow: s.pipShadow,
      setPipShadow: s.setPipShadow,
      cameraAspectRatio: s.cameraAspectRatio,
      setCameraAspectRatio: s.setCameraAspectRatio,
      customAspectRatio: s.customAspectRatio,
      setCustomAspectRatio: s.setCustomAspectRatio,
      activeInteractiveFilter: s.activeInteractiveFilter,
      setActiveInteractiveFilter: s.setActiveInteractiveFilter,
      filterIntensity: s.filterIntensity,
      setFilterIntensity: s.setFilterIntensity,
      filterColor: s.filterColor,
      setFilterColor: s.setFilterColor,
      filterTarget: s.filterTarget,
      setFilterTarget: s.setFilterTarget,
      isAutoFramingEnabled: s.isAutoFramingEnabled,
      setIsAutoFramingEnabled: s.setIsAutoFramingEnabled,
      isBeautifyEnabled: s.isBeautifyEnabled,
      setIsBeautifyEnabled: s.setIsBeautifyEnabled,
      isLowLightEnabled: s.isLowLightEnabled,
      setIsLowLightEnabled: s.setIsLowLightEnabled,
      isNeonEdgeEnabled: s.isNeonEdgeEnabled,
      setIsNeonEdgeEnabled: s.setIsNeonEdgeEnabled,
      neonIntensity: s.neonIntensity,
      setNeonIntensity: s.setNeonIntensity,
      neonColor: s.neonColor,
      setNeonColor: s.setNeonColor,
      cameraBackground: s.cameraBackground,
      setCameraBackground: s.setCameraBackground,
      customBackgroundUrl: s.customBackgroundUrl,
      setCustomBackgroundUrl: s.setCustomBackgroundUrl,
      zoomSensitivity: s.zoomSensitivity,
      setZoomSensitivity: s.setZoomSensitivity,
      trackingSpeed: s.trackingSpeed,
      setTrackingSpeed: s.setTrackingSpeed,
      isFaceTrackingEnabled: s.isFaceTrackingEnabled,
      setIsFaceTrackingEnabled: s.setIsFaceTrackingEnabled,
      canvasAspectRatio: s.canvasAspectRatio,
      setCanvasAspectRatio: s.setCanvasAspectRatio,
    })),
  );

  // --- UI Store ---
  const {
    isMouseActive,
    isFullscreen,
    setFullscreen,
    isFsSidebarOpen,
    setFsSidebarOpen,
    setShowSessionsPanel,
    showSettings,
    setShowSettings,
    isChatbotOpen,
    setChatbotOpen,
  } = useUiStore(
    useShallow((s) => ({
      isMouseActive: s.isMouseActive,
      isFullscreen: s.isFullscreen,
      setFullscreen: s.setFullscreen,
      isFsSidebarOpen: s.isFsSidebarOpen,
      setFsSidebarOpen: s.setFsSidebarOpen,
      setShowSessionsPanel: s.setShowSessionsPanel,
      showSettings: s.showSettings,
      setShowSettings: s.setShowSettings,
      isChatbotOpen: s.isChatbotOpen,
      setChatbotOpen: s.setChatbotOpen,
    })),
  );

  // Construct activeScene snapshot
  const activeScene = useMemo(
    () =>
      ({
        id: "default-scene",
        name: "Main Scene",
        isAudioOn,
        isVideoOn,
        audioDevices,
        videoDevices,
        selectedAudioDevice,
        selectedVideoDevice,
        selectedScreenSourceId,
        screenShareMode,
        layoutMode,
        cameraShape,
        splitRatio,
        pipPosition,
        pipSize,
        customMaskUrl,
        activeOverlays,
        textOverlays,
        fileOverlays,
        browserOverlays,
        emptyGridPanels,
        canvasLayout,
        backgroundEffect,
        backgroundImageUrl,
        blankCanvasColor,
        videoFilter,
        captionStyle,
        dynamicStyle,
        isAiModeEnabled,
        captionsEnabled,
        dynamicLayout,
        previousScene,
        pipRotation,
        pipBorder,
        pipShadow,
        cameraAspectRatio,
        customAspectRatio,
        activeInteractiveFilter,
        filterIntensity,
        filterColor,
        filterTarget,
        isAutoFramingEnabled,
        isBeautifyEnabled,
        isLowLightEnabled,
        isNeonEdgeEnabled,
        neonIntensity,
        neonColor,
        cameraBackground,
        customBackgroundUrl,
        zoomSensitivity,
        trackingSpeed,
        isFaceTrackingEnabled,
        canvasAspectRatio,
      }) as any,
    [
      isAudioOn,
      isVideoOn,
      audioDevices,
      videoDevices,
      selectedAudioDevice,
      selectedVideoDevice,
      selectedScreenSourceId,
      screenShareMode,
      layoutMode,
      cameraShape,
      splitRatio,
      pipPosition,
      pipSize,
      customMaskUrl,
      activeOverlays,
      textOverlays,
      fileOverlays,
      browserOverlays,
      emptyGridPanels,
      canvasLayout,
      backgroundEffect,
      backgroundImageUrl,
      blankCanvasColor,
      videoFilter,
      captionStyle,
      dynamicStyle,
      isAiModeEnabled,
      captionsEnabled,
      previousScene,
      pipRotation,
      pipBorder,
      pipShadow,
      cameraAspectRatio,
      customAspectRatio,
      activeInteractiveFilter,
      filterIntensity,
      filterColor,
      filterTarget,
      isAutoFramingEnabled,
      isBeautifyEnabled,
      isLowLightEnabled,
      isNeonEdgeEnabled,
      neonIntensity,
      neonColor,
      cameraBackground,
      customBackgroundUrl,
      zoomSensitivity,
      trackingSpeed,
      isFaceTrackingEnabled,
      canvasAspectRatio,
    ],
  );

  return {
    // Canvas store
    layoutMode,
    setLayoutMode,
    cameraShape,
    setCameraShape,
    splitRatio,
    setSplitRatio,
    pipPosition,
    setPipPosition,
    pipSize,
    setPipSize,
    isTransitioning,
    activeTransition,
    dynamicLayout,
    // Media store
    isAudioOn,
    setAudioOn,
    isVideoOn,
    setVideoOn,
    audioDevices,
    selectedAudioDevice,
    setSelectedAudioDevice,
    videoDevices,
    selectedVideoDevice,
    setSelectedVideoDevice,
    selectedScreenSourceId,
    setSelectedScreenSourceId,
    screenShareMode,
    setScreenShareMode,
    // Scene store
    customMaskUrl,
    setCustomMaskUrl,
    activeOverlays,
    setActiveOverlays,
    textOverlays,
    setTextOverlays,
    fileOverlays,
    setFileOverlays,
    browserOverlays,
    setBrowserOverlays,
    emptyGridPanels,
    setEmptyGridPanels,
    canvasLayout,
    setCanvasLayout,
    backgroundEffect,
    setBackgroundEffect,
    backgroundImageUrl,
    setBackgroundImageUrl,
    blankCanvasColor,
    setBlankCanvasColor,
    videoFilter,
    setVideoFilter,
    captionStyle,
    setCaptionStyle,
    dynamicStyle,
    setDynamicStyle,
    isAiModeEnabled,
    setAiModeEnabled,
    captionsEnabled,
    setCaptionsEnabled,
    previousScene,
    selectedBrowserId,
    setSelectedBrowserId,
    selectedFileId,
    setSelectedFileId,
    selectedTextId,
    setSelectedTextId,
    selectedGeneratedId,
    setSelectedGeneratedId,
    deselectAll,
    pipRotation,
    setPipRotation,
    pipBorder,
    setPipBorder,
    pipShadow,
    setPipShadow,
    cameraAspectRatio,
    setCameraAspectRatio,
    customAspectRatio,
    setCustomAspectRatio,
    activeInteractiveFilter,
    setActiveInteractiveFilter,
    filterIntensity,
    setFilterIntensity,
    filterColor,
    setFilterColor,
    filterTarget,
    setFilterTarget,
    isAutoFramingEnabled,
    setIsAutoFramingEnabled,
    isBeautifyEnabled,
    setIsBeautifyEnabled,
    isLowLightEnabled,
    setIsLowLightEnabled,
    isNeonEdgeEnabled,
    setIsNeonEdgeEnabled,
    neonIntensity,
    setNeonIntensity,
    neonColor,
    setNeonColor,
    cameraBackground,
    setCameraBackground,
    customBackgroundUrl,
    setCustomBackgroundUrl,
    zoomSensitivity,
    setZoomSensitivity,
    trackingSpeed,
    setTrackingSpeed,
    isFaceTrackingEnabled,
    setIsFaceTrackingEnabled,
    canvasAspectRatio,
    setCanvasAspectRatio,
    // UI store
    isMouseActive,
    isFullscreen,
    setFullscreen,
    isFsSidebarOpen,
    setFsSidebarOpen,
    setShowSessionsPanel,
    showSettings,
    setShowSettings,
    isChatbotOpen,
    setChatbotOpen,
    // Derived
    activeScene,
  };
}
