// src/lib/captionPresets.ts
import { CaptionTemplate } from "@/types/caption";

export const CAPTION_PRESETS: CaptionTemplate[] = [
  {
    id: "minimal-dark",
    name: "Minimal Dark",
    description: "Clean text with a subtle shadow.",
    preview: "https://placehold.co/600x120/1a1a1a/ffffff/png?text=Minimal+Dark",
    style: {
      fontFamily: "Inter",
      fontSize: 26,
      color: "#FFFFFF",
      backgroundColor: "rgba(0, 0, 0, 0.5)",
      position: { x: 50, y: 85 },
      shape: "rounded",
      animation: "fade",
      outline: false,
      shadow: true,
      bold: false,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#FFFFFF",
      borderWidth: 2,
    },
  },
  {
    id: "karaoke-glow",
    name: "Karaoke Glow",
    description: "Bright, clear text that slides up, styled for karaoke.",
    preview: "https://placehold.co/600x120/1e1e1e/00F5FF/png?text=Karaoke+Glow",
    style: {
      fontFamily: "Bebas Neue",
      fontSize: 48,
      color: "#00F5FF",
      backgroundColor: "rgba(30, 30, 30, 0.8)",
      position: { x: 50, y: 90 },
      shape: "rectangular",
      animation: "slide-up",
      outline: false,
      shadow: true,
      textShadow: "0 0 8px #00F5FF",
      bold: true,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#00F5FF",
      borderWidth: 2,
    },
  },
  {
    id: "news-ticker",
    name: "News Ticker",
    description: "A classic news-style lower-third banner.",
    preview: "https://placehold.co/600x120/00539C/FFFFFF/png?text=News+Ticker",
    style: {
      fontFamily: "Roboto",
      fontSize: 24,
      color: "#FFFFFF",
      backgroundColor: "rgba(0, 83, 156, 0.9)",
      position: { x: 50, y: 90 },
      shape: "banner",
      animation: "fade",
      outline: false,
      shadow: false,
      bold: true,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#FFFFFF",
      borderWidth: 2,
    },
  },
  {
    id: "cinematic-title",
    name: "Cinematic Title",
    description: "An elegant, italicized serif font for a film feel.",
    preview: "https://placehold.co/600x120/4a4a4a/f5e5c5/png?text=Cinematic+Title",
    style: {
      fontFamily: "Playfair Display",
      fontSize: 34,
      color: "#f5e5c5",
      backgroundColor: "transparent",
      position: { x: 50, y: 85 },
      shape: "rectangular",
      animation: "fade",
      outline: false,
      shadow: true,
      bold: false,
      italic: true,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#f5e5c5",
      borderWidth: 2,
    },
  },
  {
    id: "bouncy-pill",
    name: "Bouncy Pill",
    description: "A fun, energetic style with a bounce animation.",
    preview: "https://placehold.co/600x120/ff6347/ffffff/png?text=Bouncy!",
    style: {
      fontFamily: "Montserrat",
      fontSize: 32,
      color: "#FFFFFF",
      backgroundColor: "#ff6347",
      position: { x: 50, y: 50 },
      shape: "pill",
      animation: "bounce",
      outline: false,
      shadow: true,
      bold: true,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#FFFFFF",
      borderWidth: 2,
    },
  },
  {
    id: "speech-bubble",
    name: "Speech Bubble",
    description: "A casual, comic-style speech bubble.",
    preview: "https://placehold.co/600x120/ffffff/000000/png?text=Speech+Bubble",
    style: {
      fontFamily: "Inter",
      fontSize: 22,
      color: "#000000",
      backgroundColor: "#FFFFFF",
      position: { x: 50, y: 70 },
      shape: "speech-bubble",
      animation: "fade",
      outline: false,
      shadow: true,
      bold: false,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#000000",
      borderWidth: 2,
    },
  },
];