// src/lib/captionPresets.ts
import { CaptionTemplate } from "@/types/caption";

export const CAPTION_PRESETS: CaptionTemplate[] = [
  // --- EXISTING PRESETS ---
  {
    id: "minimal-dark",
    name: "Minimal Dark",
    description: "Clean text with a subtle shadow.",
    preview: "https://placehold.co/600x120/1a1a1a/ffffff/png?text=Minimal+Dark",
    style: {
      fontFamily: "Inter",
      fontSize: 26,
      color: "#FFFFFF",
      backgroundColor: "rgba(0, 0, 0, 0.5)",
      position: { x: 50, y: 85 },
      shape: "rounded",
      animation: "fade",
      outline: false,
      shadow: true,
      bold: false,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#FFFFFF",
      borderWidth: 2,
    },
  },
  {
    id: "karaoke-glow",
    name: "Karaoke Glow",
    description: "Bright, clear text that slides up, styled for karaoke.",
    preview: "https://placehold.co/600x120/1e1e1e/00F5FF/png?text=Karaoke+Glow",
    style: {
      fontFamily: "Bebas Neue",
      fontSize: 48,
      color: "#00F5FF",
      backgroundColor: "rgba(30, 30, 30, 0.8)",
      position: { x: 50, y: 90 },
      shape: "rectangular",
      animation: "slide-up",
      outline: false,
      shadow: true,
      textShadow: "0 0 8px #00F5FF",
      bold: true,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#00F5FF",
      borderWidth: 2,
    },
  },
  {
    id: "news-ticker",
    name: "News Ticker",
    description: "A classic news-style lower-third banner.",
    preview: "https://placehold.co/600x120/00539C/FFFFFF/png?text=News+Ticker",
    style: {
      fontFamily: "Roboto",
      fontSize: 24,
      color: "#FFFFFF",
      backgroundColor: "rgba(0, 83, 156, 0.9)",
      position: { x: 50, y: 90 },
      shape: "banner",
      animation: "fade",
      outline: false,
      shadow: false,
      bold: true,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#FFFFFF",
      borderWidth: 2,
    },
  },
  {
    id: "cinematic-title",
    name: "Cinematic Title",
    description: "An elegant, italicized serif font for a film feel.",
    preview:
      "https://placehold.co/600x120/4a4a4a/f5e5c5/png?text=Cinematic+Title",
    style: {
      fontFamily: "Playfair Display",
      fontSize: 34,
      color: "#f5e5c5",
      backgroundColor: "transparent",
      position: { x: 50, y: 85 },
      shape: "rectangular",
      animation: "fade",
      outline: false,
      shadow: true,
      bold: false,
      italic: true,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#f5e5c5",
      borderWidth: 2,
    },
  },
  {
    id: "bouncy-pill",
    name: "Bouncy Pill",
    description: "A fun, energetic style with a bounce animation.",
    preview: "https://placehold.co/600x120/ff6347/ffffff/png?text=Bouncy!",
    style: {
      fontFamily: "Montserrat",
      fontSize: 32,
      color: "#FFFFFF",
      backgroundColor: "#ff6347",
      position: { x: 50, y: 50 },
      shape: "pill",
      animation: "bounce",
      outline: false,
      shadow: true,
      bold: true,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#FFFFFF",
      borderWidth: 2,
    },
  },
  {
    id: "speech-bubble",
    name: "Speech Bubble",
    description: "A casual, comic-style speech bubble.",
    preview:
      "https://placehold.co/600x120/ffffff/000000/png?text=Speech+Bubble",
    style: {
      fontFamily: "Inter",
      fontSize: 22,
      color: "#000000",
      backgroundColor: "#FFFFFF",
      position: { x: 50, y: 70 },
      shape: "speech-bubble",
      animation: "fade",
      outline: false,
      shadow: true,
      bold: false,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#000000",
      borderWidth: 2,
    },
  },

  // --- ADDED 50 NEW PRESETS ---

  // --- Gaming & Tech ---
  {
    id: "gaming-green-glow",
    name: "Gaming Green",
    description: "A sharp, tech font with a bright green glow.",
    preview: "https://placehold.co/600x120/1a1a1a/39FF14/png?text=Gaming+Green",
    style: {
      fontFamily: "Orbitron",
      fontSize: 38,
      color: "#39FF14",
      backgroundColor: "rgba(0, 0, 0, 0.7)",
      position: { x: 50, y: 88 },
      shape: "rectangular",
      animation: "fade",
      outline: false,
      shadow: true,
      textShadow: "0 0 10px #39FF14, 0 0 20px #39FF14",
      bold: true,
      italic: false,
      underline: false,
      rotation: 0,
      border: true,
      borderColor: "#39FF14",
      borderWidth: 1,
    },
  },
  {
    id: "cyber-magenta",
    name: "Cyber Magenta",
    description: "A futuristic font with a striking magenta color.",
    preview:
      "https://placehold.co/600x120/0a0a0a/FF00FF/png?text=Cyber+Magenta",
    style: {
      fontFamily: "Michroma",
      fontSize: 36,
      color: "#FF00FF",
      backgroundColor: "transparent",
      position: { x: 50, y: 50 },
      shape: "rectangular",
      animation: "fade",
      outline: true,
      shadow: true,
      textShadow: "0 0 8px #FF00FF",
      bold: false,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#FF00FF",
      borderWidth: 2,
    },
  },
  {
    id: "pixel-perfect",
    name: "Pixel Perfect",
    description: "A retro, pixelated font style.",
    preview:
      "https://placehold.co/600x120/333333/FFFFFF/png?text=Pixel+Perfect",
    style: {
      fontFamily: "Press Start 2P",
      fontSize: 24,
      color: "#FFFFFF",
      backgroundColor: "rgba(30, 30, 30, 0.8)",
      position: { x: 50, y: 85 },
      shape: "rounded",
      animation: "fade",
      outline: false,
      shadow: false,
      bold: false,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#FFFFFF",
      borderWidth: 2,
    },
  },
  {
    id: "digital-blue",
    name: "Digital Blue",
    description: "A clean, digital-style blue text.",
    preview: "https://placehold.co/600x120/050a20/00C4FF/png?text=Digital+Blue",
    style: {
      fontFamily: "Share Tech Mono",
      fontSize: 30,
      color: "#00C4FF",
      backgroundColor: "rgba(5, 10, 32, 0.8)",
      position: { x: 50, y: 90 },
      shape: "banner",
      animation: "slide-up",
      outline: false,
      shadow: true,
      bold: false,
      italic: false,
      underline: false,
      rotation: 0,
      border: true,
      borderColor: "#00C4FF",
      borderWidth: 1,
    },
  },
  {
    id: "arcade-bouncy",
    name: "Arcade Bouncy",
    description: "A fun, bold, and bouncy arcade-style text.",
    preview:
      "https://placehold.co/600x120/FFD700/000000/png?text=Arcade+Bouncy",
    style: {
      fontFamily: "Bungee",
      fontSize: 40,
      color: "#000000",
      backgroundColor: "#FFD700",
      position: { x: 50, y: 50 },
      shape: "pill",
      animation: "bounce",
      outline: false,
      shadow: true,
      bold: true,
      italic: false,
      underline: false,
      rotation: 0,
      border: true,
      borderColor: "#000000",
      borderWidth: 3,
    },
  },

  // --- Elegant & Cinematic ---
  {
    id: "elegant-gold",
    name: "Elegant Gold",
    description: "A classic serif font with a subtle gold touch.",
    preview: "https://placehold.co/600x120/fdfbf7/D4AF37/png?text=Elegant+Gold",
    style: {
      fontFamily: "Playfair Display",
      fontSize: 34,
      color: "#D4AF37",
      backgroundColor: "transparent",
      position: { x: 50, y: 50 },
      shape: "rectangular",
      animation: "fade",
      outline: false,
      shadow: true,
      textShadow: "0 1px 3px rgba(0,0,0,0.4)",
      bold: false,
      italic: true,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#D4AF37",
      borderWidth: 2,
    },
  },
  {
    id: "minimal-serif",
    name: "Minimal Serif",
    description: "A clean, modern serif font.",
    preview:
      "https://placehold.co/600x120/1a1a1a/EEEEEE/png?text=Minimal+Serif",
    style: {
      fontFamily: "Lora",
      fontSize: 28,
      color: "#EEEEEE",
      backgroundColor: "rgba(0,0,0,0.6)",
      position: { x: 50, y: 85 },
      shape: "rounded",
      animation: "fade",
      outline: false,
      shadow: false,
      bold: false,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#EEEEEE",
      borderWidth: 2,
    },
  },
  {
    id: "cinematic-wide",
    name: "Cinematic Wide",
    description: "A wide, bold title for cinematic feel.",
    preview:
      "https://placehold.co/600x120/000000/FFFFFF/png?text=Cinematic+Wide",
    style: {
      fontFamily: "Cinzel",
      fontSize: 42,
      color: "#FFFFFF",
      backgroundColor: "transparent",
      position: { x: 50, y: 80 },
      shape: "rectangular",
      animation: "fade",
      outline: false,
      shadow: true,
      textShadow: "0 2px 5px rgba(0,0,0,0.8)",
      bold: true,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#FFFFFF",
      borderWidth: 2,
    },
  },
  {
    id: "gothic-story",
    name: "Gothic Story",
    description: "An old-style font for a dramatic effect.",
    preview: "https://placehold.co/600x120/222222/f0e6d2/png?text=Gothic+Story",
    style: {
      fontFamily: "Uncial Antiqua",
      fontSize: 36,
      color: "#f0e6d2",
      backgroundColor: "transparent",
      position: { x: 50, y: 50 },
      shape: "rectangular",
      animation: "fade",
      outline: false,
      shadow: true,
      bold: false,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#f0e6d2",
      borderWidth: 2,
    },
  },
  {
    id: "author-quote",
    name: "Author Quote",
    description: "An italic serif, perfect for quoting.",
    preview: "https://placehold.co/600x120/f5f5f5/333333/png?text=Author+Quote",
    style: {
      fontFamily: "PT Serif",
      fontSize: 26,
      color: "#333333",
      backgroundColor: "rgba(245, 245, 245, 0.8)",
      position: { x: 50, y: 50 },
      shape: "rounded",
      animation: "fade",
      outline: false,
      shadow: false,
      bold: false,
      italic: true,
      underline: false,
      rotation: 0,
      border: true,
      borderColor: "#333333",
      borderWidth: 1,
    },
  },

  // --- Vlog & Handwritten ---
  {
    id: "vlog-note",
    name: "Vlog Note",
    description: "A casual, handwritten style for vlogs.",
    preview: "https://placehold.co/600x120/ffffff/1a1a1a/png?text=Vlog+Note",
    style: {
      fontFamily: "Caveat",
      fontSize: 36,
      color: "#1a1a1a",
      backgroundColor: "rgba(255, 255, 255, 0.9)",
      position: { x: 50, y: 50 },
      shape: "rounded",
      animation: "bounce",
      outline: false,
      shadow: true,
      bold: true,
      italic: false,
      underline: false,
      rotation: -2,
      border: false,
      borderColor: "#1a1a1a",
      borderWidth: 2,
    },
  },
  {
    id: "marker-scribble",
    name: "Marker Scribble",
    description: "A thick, permanent marker style.",
    preview:
      "https://placehold.co/600x120/ffff99/000000/png?text=Marker+Scribble",
    style: {
      fontFamily: "Permanent Marker",
      fontSize: 32,
      color: "#000000",
      backgroundColor: "rgba(255, 255, 153, 0.9)",
      position: { x: 50, y: 30 },
      shape: "rounded",
      animation: "fade",
      outline: false,
      shadow: false,
      bold: false,
      italic: false,
      underline: false,
      rotation: 2,
      border: false,
      borderColor: "#000000",
      borderWidth: 2,
    },
  },
  {
    id: "indie-flower",
    name: "Indie Flower",
    description: "A friendly, rounded handwritten font.",
    preview: "https://placehold.co/600x120/333333/FFFFFF/png?text=Indie+Flower",
    style: {
      fontFamily: "Indie Flower",
      fontSize: 30,
      color: "#FFFFFF",
      backgroundColor: "rgba(50, 50, 50, 0.8)",
      position: { x: 50, y: 85 },
      shape: "pill",
      animation: "fade",
      outline: false,
      shadow: false,
      bold: false,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#FFFFFF",
      borderWidth: 2,
    },
  },
  {
    id: "cursive-script",
    name: "Cursive Script",
    description: "An elegant, flowing script.",
    preview:
      "https://placehold.co/600x120/fdeeee/c70039/png?text=Cursive+Script",
    style: {
      fontFamily: "Dancing Script",
      fontSize: 38,
      color: "#c70039",
      backgroundColor: "transparent",
      position: { x: 50, y: 50 },
      shape: "rectangular",
      animation: "fade",
      outline: false,
      shadow: true,
      bold: true,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#c70039",
      borderWidth: 2,
    },
  },
  {
    id: "architect-draft",
    name: "Architect Draft",
    description: "A neat, architectural handwriting style.",
    preview:
      "https://placehold.co/600x120/1e3a8a/dbeafe/png?text=Architect+Draft",
    style: {
      fontFamily: "Architects Daughter",
      fontSize: 26,
      color: "#dbeafe",
      backgroundColor: "rgba(30, 58, 138, 0.9)",
      position: { x: 50, y: 15 },
      shape: "banner",
      animation: "fade",
      outline: false,
      shadow: false,
      bold: false,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#dbeafe",
      borderWidth: 2,
    },
  },

  // --- Bold & Impactful ---
  {
    id: "impact-heavy",
    name: "Impact Heavy",
    description: "A thick, bold, all-caps font.",
    preview: "https://placehold.co/600x120/ffffff/000000/png?text=IMPACT+HEAVY",
    style: {
      fontFamily: "Anton",
      fontSize: 52,
      color: "#000000",
      backgroundColor: "rgba(255, 255, 255, 0.9)",
      position: { x: 50, y: 50 },
      shape: "rectangular",
      animation: "fade",
      outline: false,
      shadow: false,
      bold: true,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#000000",
      borderWidth: 2,
    },
  },
  {
    id: "oswald-condensed",
    name: "Oswald Condensed",
    description: "A condensed, strong font for statements.",
    preview:
      "https://placehold.co/600x120/c70039/ffffff/png?text=Oswald+Condensed",
    style: {
      fontFamily: "Oswald",
      fontSize: 40,
      color: "#FFFFFF",
      backgroundColor: "rgba(199, 0, 57, 0.9)",
      position: { x: 50, y: 88 },
      shape: "rectangular",
      animation: "slide-up",
      outline: false,
      shadow: true,
      bold: true,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#FFFFFF",
      borderWidth: 2,
    },
  },
  {
    id: "passion-one-black",
    name: "Passion One Black",
    description: "A very heavy, impactful font.",
    preview: "https://placehold.co/600x120/111111/f5b300/png?text=Passion+One",
    style: {
      fontFamily: "Passion One",
      fontSize: 56,
      color: "#f5b300",
      backgroundColor: "transparent",
      position: { x: 50, y: 50 },
      shape: "rectangular",
      animation: "fade",
      outline: true,
      shadow: true,
      bold: true,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#f5b300",
      borderWidth: 2,
    },
  },
  {
    id: "russo-one-solid",
    name: "Russo One Solid",
    description: "A solid, wide, and modern font.",
    preview: "https://placehold.co/600x120/005f73/94d2bd/png?text=Russo+One",
    style: {
      fontFamily: "Russo One",
      fontSize: 38,
      color: "#94d2bd",
      backgroundColor: "rgba(0, 95, 115, 0.9)",
      position: { x: 50, y: 85 },
      shape: "rounded",
      animation: "fade",
      outline: false,
      shadow: true,
      bold: false,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#94d2bd",
      borderWidth: 2,
    },
  },
  {
    id: "staatliches-poster",
    name: "Staatliches Poster",
    description: "A bold, poster-style display font.",
    preview: "https://placehold.co/600x120/e0e0e0/d90429/png?text=Staatliches",
    style: {
      fontFamily: "Staatliches",
      fontSize: 54,
      color: "#d90429",
      backgroundColor: "rgba(224, 224, 224, 0.9)",
      position: { x: 50, y: 50 },
      shape: "rectangular",
      animation: "fade",
      outline: false,
      shadow: false,
      bold: false,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#d90429",
      borderWidth: 2,
    },
  },

  // --- Fun & Quirky ---
  {
    id: "luckiest-guy-cartoon",
    name: "Luckiest Guy",
    description: "A fun, heavy cartoon-style font.",
    preview: "https://placehold.co/600x120/00b4d8/ffffff/png?text=LUCKIEST+GUY",
    style: {
      fontFamily: "Luckiest Guy",
      fontSize: 44,
      color: "#FFFFFF",
      backgroundColor: "rgba(0, 180, 216, 0.9)",
      position: { x: 50, y: 50 },
      shape: "pill",
      animation: "bounce",
      outline: true,
      shadow: true,
      bold: false,
      italic: false,
      underline: false,
      rotation: -3,
      border: false,
      borderColor: "#FFFFFF",
      borderWidth: 2,
    },
  },
  {
    id: "shrikhand-playful",
    name: "Shrikhand Playful",
    description: "A playful, rounded, and bold font.",
    preview: "https://placehold.co/600x120/f72585/ffffff/png?text=Shrikhand",
    style: {
      fontFamily: "Shrikhand",
      fontSize: 38,
      color: "#FFFFFF",
      backgroundColor: "rgba(247, 37, 133, 0.9)",
      position: { x: 50, y: 50 },
      shape: "rounded",
      animation: "bounce",
      outline: false,
      shadow: true,
      bold: false,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#FFFFFF",
      borderWidth: 2,
    },
  },
  {
    id: "rubik-bubbles",
    name: "Rubik Bubbles",
    description: "A unique, bubbly font.",
    preview: "https://placehold.co/600x120/4361ee/ffffff/png?text=Bubbles",
    style: {
      fontFamily: "Rubik Bubbles",
      fontSize: 40,
      color: "#FFFFFF",
      backgroundColor: "rgba(67, 97, 238, 0.8)",
      position: { x: 50, y: 50 },
      shape: "pill",
      animation: "bounce",
      outline: false,
      shadow: false,
      bold: false,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#FFFFFF",
      borderWidth: 2,
    },
  },
  {
    id: "creepy-horror",
    name: "Creepy Horror",
    description: "A spooky, horror-themed font.",
    preview: "https://placehold.co/600x120/000000/dc2f02/png?text=Creepy",
    style: {
      fontFamily: "Creepster",
      fontSize: 48,
      color: "#dc2f02",
      backgroundColor: "rgba(0, 0, 0, 0.8)",
      position: { x: 50, y: 50 },
      shape: "rounded",
      animation: "fade",
      outline: false,
      shadow: true,
      textShadow: "0 0 5px #dc2f02",
      bold: false,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#dc2f02",
      borderWidth: 2,
    },
  },
  {
    id: "western-saloon",
    name: "Western Saloon",
    description: "A classic, old-west style font.",
    preview:
      "https://placehold.co/600x120/582f0e/fdf0d5/png?text=Western+Saloon",
    style: {
      fontFamily: "Rye",
      fontSize: 36,
      color: "#fdf0d5",
      backgroundColor: "rgba(88, 47, 14, 0.8)",
      position: { x: 50, y: 85 },
      shape: "rectangular",
      animation: "fade",
      outline: false,
      shadow: true,
      bold: false,
      italic: false,
      underline: false,
      rotation: 0,
      border: true,
      borderColor: "#fdf0d5",
      borderWidth: 2,
    },
  },

  // --- 5 More Style Varieties ---
  {
    id: "clean-outline",
    name: "Clean Outline",
    description: "Transparent background with a clean white outline.",
    preview:
      "https://placehold.co/600x120/aaaaaa/FFFFFF/png?text=Clean+Outline",
    style: {
      fontFamily: "Inter",
      fontSize: 32,
      color: "#FFFFFF",
      backgroundColor: "transparent",
      position: { x: 50, y: 85 },
      shape: "rectangular",
      animation: "fade",
      outline: true,
      shadow: true,
      textShadow: "0 1px 3px rgba(0,0,0,0.8)",
      bold: true,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#FFFFFF",
      borderWidth: 2,
    },
  },
  {
    id: "yellow-box",
    name: "Yellow Box",
    description: "Bright yellow box with bold black text.",
    preview: "https://placehold.co/600x120/fde047/1e293b/png?text=Yellow+Box",
    style: {
      fontFamily: "Montserrat",
      fontSize: 28,
      color: "#1e293b",
      backgroundColor: "#fde047",
      position: { x: 50, y: 15 },
      shape: "rounded",
      animation: "slide-up",
      outline: false,
      shadow: true,
      bold: true,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#1e293b",
      borderWidth: 2,
    },
  },
  {
    id: "pink-pill-pop",
    name: "Pink Pill Pop",
    description: "A soft pink pill shape.",
    preview: "https://placehold.co/600x120/f9a8d4/1f2937/png?text=Pink+Pill",
    style: {
      fontFamily: "Open Sans",
      fontSize: 26,
      color: "#1f2937",
      backgroundColor: "#f9a8d4",
      position: { x: 50, y: 85 },
      shape: "pill",
      animation: "fade",
      outline: false,
      shadow: false,
      bold: true,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#1f2937",
      borderWidth: 2,
    },
  },
  {
    id: "simple-border",
    name: "Simple Border",
    description: "Transparent fill with a simple border.",
    preview:
      "https://placehold.co/600x120/333333/FFFFFF/png?text=Simple+Border",
    style: {
      fontFamily: "Roboto",
      fontSize: 28,
      color: "#FFFFFF",
      backgroundColor: "transparent",
      position: { x: 50, y: 50 },
      shape: "rounded",
      animation: "fade",
      outline: false,
      shadow: false,
      bold: false,
      italic: false,
      underline: false,
      rotation: 0,
      border: true,
      borderColor: "#FFFFFF",
      borderWidth: 3,
    },
  },
  {
    id: "faded-text",
    name: "Faded Text",
    description: "Subtle text with low opacity background.",
    preview: "https://placehold.co/600x120/111111/bbbbbb/png?text=Faded+Text",
    style: {
      fontFamily: "Inter",
      fontSize: 22,
      color: "#bbbbbb",
      backgroundColor: "rgba(0, 0, 0, 0.2)",
      position: { x: 50, y: 88 },
      shape: "rounded",
      animation: "fade",
      outline: false,
      shadow: false,
      bold: false,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#bbbbbb",
      borderWidth: 2,
    },
  },

  // --- 5 More Style Varieties ---
  {
    id: "red-alert-banner",
    name: "Red Alert Banner",
    description: "A full-width red banner for alerts.",
    preview: "https://placehold.co/600x120/dc2626/ffffff/png?text=Red+Alert",
    style: {
      fontFamily: "Bebas Neue",
      fontSize: 40,
      color: "#FFFFFF",
      backgroundColor: "rgba(220, 38, 38, 0.9)",
      position: { x: 50, y: 10 },
      shape: "banner",
      animation: "fade",
      outline: false,
      shadow: true,
      bold: true,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#FFFFFF",
      borderWidth: 2,
    },
  },
  {
    id: "green-success-pill",
    name: "Green Success",
    description: "A friendly green pill for success messages.",
    preview: "https://placehold.co/600x120/16a34a/ffffff/png?text=Success!",
    style: {
      fontFamily: "Montserrat",
      fontSize: 28,
      color: "#FFFFFF",
      backgroundColor: "#16a34a",
      position: { x: 50, y: 50 },
      shape: "pill",
      animation: "bounce",
      outline: false,
      shadow: true,
      bold: true,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#FFFFFF",
      borderWidth: 2,
    },
  },
  {
    id: "purple-gradient",
    name: "Purple Gradient",
    description: "A bold text with a purple gradient.",
    preview:
      "https://placehold.co/600x120/1e1b4b/c084fc/png?text=Purple+Gradient",
    style: {
      fontFamily: "Exo 2",
      fontSize: 42,
      color: "#c084fc",
      backgroundColor: "transparent",
      position: { x: 50, y: 50 },
      shape: "rectangular",
      animation: "fade",
      outline: false,
      shadow: true,
      gradient: "linear-gradient(90deg, #a855f7, #6366f1)",
      textShadow: "0 0 10px #a855f7",
      bold: true,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#c084fc",
      borderWidth: 2,
    },
  },
  {
    id: "orange-outline-bold",
    name: "Orange Outline",
    description: "Thick text with an orange outline.",
    preview:
      "https://placehold.co/600x120/4a4a4a/f97316/png?text=Orange+Outline",
    style: {
      fontFamily: "Impact",
      fontSize: 48,
      color: "#f97316",
      backgroundColor: "transparent",
      position: { x: 50, y: 50 },
      shape: "rectangular",
      animation: "fade",
      outline: true,
      shadow: true,
      textShadow: "0 2px 2px #000000",
      bold: true,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#f97316",
      borderWidth: 2,
    },
  },
  {
    id: "classic-typewriter",
    name: "Classic Typewriter",
    description: "A simple, classic typewriter font.",
    preview:
      "https://placehold.co/600x120/f1f1f1/222222/png?text=Classic+Typewriter",
    style: {
      fontFamily: "Courier New",
      fontSize: 26,
      color: "#222222",
      backgroundColor: "rgba(241, 241, 241, 0.8)",
      position: { x: 50, y: 80 },
      shape: "rounded",
      animation: "fade",
      outline: false,
      shadow: false,
      bold: false,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#222222",
      borderWidth: 2,
    },
  },

  // --- 5 More Style Varieties ---
  {
    id: "comic-book",
    name: "Comic Book",
    description: "A fun, comic-book style.",
    preview: "https://placehold.co/600x120/ffffff/000000/png?text=Comic+Book",
    style: {
      fontFamily: "Comic Sans MS",
      fontSize: 30,
      color: "#000000",
      backgroundColor: "rgba(255, 255, 255, 0.9)",
      position: { x: 50, y: 50 },
      shape: "rounded",
      animation: "bounce",
      outline: false,
      shadow: false,
      bold: true,
      italic: false,
      underline: false,
      rotation: 1,
      border: true,
      borderColor: "#000000",
      borderWidth: 3,
    },
  },
  {
    id: "sleek-modern",
    name: "Sleek Modern",
    description: "A thin, light, and modern font.",
    preview: "https://placehold.co/600x120/0a0a0a/e5e5e5/png?text=Sleek+Modern",
    style: {
      fontFamily: "Kanit",
      fontSize: 28,
      color: "#e5e5e5",
      backgroundColor: "rgba(10, 10, 10, 0.7)",
      position: { x: 50, y: 90 },
      shape: "banner",
      animation: "slide-up",
      outline: false,
      shadow: false,
      bold: false,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#e5e5e5",
      borderWidth: 2,
    },
  },
  {
    id: "journal-entry",
    name: "Journal Entry",
    description: "A personal, script-like font.",
    preview:
      "https://placehold.co/600x120/faf3e0/4a3f35/png?text=Journal+Entry",
    style: {
      fontFamily: "Kalam",
      fontSize: 28,
      color: "#4a3f35",
      backgroundColor: "rgba(250, 243, 224, 0.9)",
      position: { x: 50, y: 50 },
      shape: "rounded",
      animation: "fade",
      outline: false,
      shadow: false,
      bold: false,
      italic: false,
      underline: false,
      rotation: -1,
      border: false,
      borderColor: "#4a3f35",
      borderWidth: 2,
    },
  },
  {
    id: "retro-wave",
    name: "Retro Wave",
    description: "A retro 80s style with pink and blue.",
    preview: "https://placehold.co/600x120/0f0c29/f920f2/png?text=Retro+Wave",
    style: {
      fontFamily: "Monoton",
      fontSize: 40,
      color: "#f920f2",
      backgroundColor: "transparent",
      position: { x: 50, y: 50 },
      shape: "rectangular",
      animation: "fade",
      outline: false,
      shadow: true,
      textShadow: "0 0 5px #f920f2, 0 0 10px #00c4ff",
      bold: false,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#f920f2",
      borderWidth: 2,
    },
  },
  {
    id: "chalkboard",
    name: "Chalkboard",
    description: "A handwritten font on a dark background.",
    preview: "https://placehold.co/600x120/36454f/ffffff/png?text=Chalkboard",
    style: {
      fontFamily: "Gochi Hand",
      fontSize: 32,
      color: "#FFFFFF",
      backgroundColor: "rgba(54, 69, 79, 0.9)",
      position: { x: 50, y: 50 },
      shape: "rounded",
      animation: "fade",
      outline: false,
      shadow: false,
      bold: false,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#FFFFFF",
      borderWidth: 2,
    },
  },

  // --- 5 More Style Varieties ---
  {
    id: "shadow-block",
    name: "Shadow Block",
    description: "Text with a heavy block shadow.",
    preview: "https://placehold.co/600x120/ffffff/444444/png?text=Shadow+Block",
    style: {
      fontFamily: "Alfa Slab One",
      fontSize: 46,
      color: "#FFFFFF",
      backgroundColor: "transparent",
      position: { x: 50, y: 50 },
      shape: "rectangular",
      animation: "fade",
      outline: false,
      shadow: true,
      textShadow: "4px 4px 0px #444444",
      bold: false,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#FFFFFF",
      borderWidth: 2,
    },
  },
  {
    id: "inverted-pill",
    name: "Inverted Pill",
    description: "A dark pill with bright text.",
    preview:
      "https://placehold.co/600x120/222222/f0f0f0/png?text=Inverted+Pill",
    style: {
      fontFamily: "Inter",
      fontSize: 24,
      color: "#f0f0f0",
      backgroundColor: "#222222",
      position: { x: 50, y: 85 },
      shape: "pill",
      animation: "fade",
      outline: false,
      shadow: true,
      bold: true,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#f0f0f0",
      borderWidth: 2,
    },
  },
  {
    id: "formal-invite",
    name: "Formal Invite",
    description: "An elegant, thin script.",
    preview:
      "https://placehold.co/600x120/ffffff/0a0a0a/png?text=Formal+Invite",
    style: {
      fontFamily: "Great Vibes",
      fontSize: 40,
      color: "#0a0a0a",
      backgroundColor: "transparent",
      position: { x: 50, y: 50 },
      shape: "rectangular",
      animation: "fade",
      outline: false,
      shadow: false,
      bold: false,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#0a0a0a",
      borderWidth: 2,
    },
  },
  {
    id: "corporate-blue",
    name: "Corporate Blue",
    description: "A clean, sans-serif font for business.",
    preview:
      "https://placehold.co/600x120/f0f9ff/0284c7/png?text=Corporate+Blue",
    style: {
      fontFamily: "Open Sans",
      fontSize: 26,
      color: "#0284c7",
      backgroundColor: "rgba(240, 249, 255, 0.9)",
      position: { x: 50, y: 85 },
      shape: "rounded",
      animation: "fade",
      outline: false,
      shadow: false,
      bold: true,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#0284c7",
      borderWidth: 2,
    },
  },
  {
    id: "minimal-light",
    name: "Minimal Light",
    description: "A thin, light font on a light background.",
    preview:
      "https://placehold.co/600x120/e5e5e5/525252/png?text=Minimal+Light",
    style: {
      fontFamily: "Roboto",
      fontSize: 24,
      color: "#525252",
      backgroundColor: "rgba(229, 229, 229, 0.7)",
      position: { x: 50, y: 85 },
      shape: "rounded",
      animation: "fade",
      outline: false,
      shadow: false,
      bold: false,
      italic: false,
      underline: false,
      rotation: 0,
      border: false,
      borderColor: "#525252",
      borderWidth: 2,
    },
  },
];
