// src/lib/fonts.ts

export const ALL_FONTS: string[] = [
  // --- CORE APP FONTS (Keep at top for stability) ---
  "Inter",
  "Roboto",
  "Open Sans",
  "Montserrat",
  "Playfair Display",
  "Bebas Neue",

  // --- SANS-SERIF (Modern, Clean) ---
  "Poppins",
  "Raleway",
  "Lato",
  "Nunito",
  "Work Sans",
  "Rubik",
  "Quicksand",
  "Outfit",
  "Manrope",
  "DM Sans",
  "Plus Jakarta Sans",
  "Lexend",
  "Figtree",
  "Sora",
  "Space Grotesk",
  "Onest",

  // --- HIGH IMPACT & DISPLAY (CapCut/YouTube Title Style) ---
  "Anton",
  "Oswald",
  "Passion One",
  "Russo One",
  "Staatliches",
  "Kanit",
  "Exo 2",
  "Prompt",
  "Ultra",
  "Abril Fatface",
  "Squada One",
  "Righteous",
  "Monoton",
  "Changa",
  "Racing Sans One",
  "Titan One",
  "Bowlby One",
  "Alfa Slab One",
  "Shrikhand",
  "Luckiest Guy",
  "Caveat Brush",
  "Permanent Marker",
  "Faster One",
  "Aclonica",
  "Gugi",
  "Wallpoet",
  "Bungee Shade",
  "Fredoka One",
  "Lilita One",
  "Patua One",
  "Sigmar One",
  "Black Ops One",
  "Concert One",

  // --- GAMING & TECH (Cyberpunk, Arcade, Retro) ---
  "Michroma",
  "Orbitron",
  "Quantico",
  "VT323",
  "Press Start 2P",
  "Bungee",
  "Electrolize",
  "Major Mono Display",
  "Zen Dots",
  "Space Mono",
  "Codystar",
  "Iceland",
  "Share Tech Mono",
  "Audiowide",
  "Syncopate",
  "Saira",
  "Teko",
  "Aldrich",
  "Chakra Petch",

  // --- HANDWRITING & SCRIPT (Casual, Vlog, Personal) ---
  "Pacifico",
  "Dancing Script",
  "Great Vibes",
  "Sacramento",
  "Tangerine",
  "Indie Flower",
  "Kalam",
  "Caveat",
  "Handlee",
  "Architects Daughter",
  "Gochi Hand",
  "Reenie Beanie",
  "Shadows Into Light",
  "Sue Ellen Francisco",
  "Nothing You Could Do",
  "Zeyada",
  "Amatic SC",
  "Homemade Apple",
  "Satisfy",
  "Cookie",
  "Allura",
  "Alex Brush",
  "Monsieur La Doulaise",
  "La Belle Aurore",
  "Mr Dafoe",
  "Yellowtail",
  "Kaushan Script",
  "Courgette",
  "Marck Script",

  // --- SERIF (Elegant, Cinematic, Classic) ---
  "Merriweather",
  "Lora",
  "PT Serif",
  "Cormorant Garamond",
  "Tinos",
  "Libre Baskerville",
  "Domine",
  "EB Garamond",
  "Faustina",
  "Literata",
  "Source Serif 4",
  "Alegreya",
  "Caudex",
  "Gilda Display",
  "Uncial Antiqua",
  "Limelight",
  "Cinzel",
  "Crimson Text",
  "Spectral",
  "Bitter",
  "Cardo",
  "Vollkorn",
  "Arvo",
  "Rokkitt",
  "Noto Serif",
  "Gelasio",

  // --- DECORATIVE & UNIQUE (Distinctive Shapes) ---
  "Rubik Bubbles",
  "Metal Mania",
  "Creepster",
  "Nosifer",
  "Rye",
  "Graduate",
  "Chonburi",
  "Fugaz One",
  "Unica One",
  "Krona One",
  "Megrim",
  "Stint Ultra Condensed",
  "Vidaloka",
  "Butcherman",
  "Mystery Quest",
  "Smokum",
  "Finger Paint",
  "Freckle Face",
  "Irish Grover",
  "Bungee Inline",
  "Rammetto One",
  "Diplomata",
  "Bubbler One",
  "Eater",
  "Henny Penny",
  "Jolly Lodger",
  "Kavoon",
  "Londrina Solid",
  "Modak",
  "Shojumaru",
  "Special Elite",

  // --- MONOSPACE (Code, Technical) ---
  "Roboto Mono",
  "Source Code Pro",
  "JetBrains Mono",
  "Fira Code",
  "IBM Plex Mono",
  "Inconsolata",
  "Ubuntu Mono",
  "Courier Prime",
  "Anonymous Pro",
  "Nanum Gothic Coding",
];
