// src/lib/fonts.ts

export const ALL_FONTS: string[] = [
  // --- CORE APP FONTS (Keep at top for stability) ---
  "Inter",
  "Roboto",
  "Open Sans",
  "Montserrat",
  "Playfair Display",
  "Bebas Neue",
  // --- HIGH IMPACT & DISPLAY (CapCut/YouTube Title Style) ---
  "Anton",
  "Oswald",
  "Passion One",
  "Russo One",
  "Staatliches",
  "Kanit",
  "Exo 2",
  "Prompt",
  "Ultra",
  "Monoton",
  "Abril Fatface",
  "Squada One",
  "Righteous",
  "Monoton",
  "Changa",
  "Racing Sans One",
  "Titan One",
  "Bowlby One",
  "Alfa Slab One",
  "Shrikhand",
  "Luckiest Guy",
  "Caveat Brush",
  "Permanent Marker",
  "Faster One",
  "Aclonica",
  "Gugi",
  "Wallpoet",
  // --- GAMING & TECH (Cyberpunk, Arcade, Retro) ---
  "Michroma",
  "Orbitron",
  "Quantico",
  "VT323",
  "Press Start 2P",
  "Bungee",
  "Electrolize",
  "Major Mono Display",
  "Zen Dots",
  "Space Mono",
  "Codystar",
  "Electrolize",
  "Geo",
  "Iceland",
  "Digital Numbers", // Not a real Google Font, but used for effect
  "Share Tech Mono",
  // --- HANDWRITING & SCRIPT (Casual, Vlog, Personal) ---
  "Pacifico",
  "Dancing Script",
  "Great Vibes",
  "Sacramento",
  "Tangerine",
  "Indie Flower",
  "Kalam",
  "Caveat",
  "Handlee",
  "Architects Daughter",
  "Gochi Hand",
  "Reenie Beanie",
  "Shadows Into Light",
  "Sue Ellen Francisco",
  "Nothing You Could Do",
  "Zeyada",
  "Amatic SC",
  "Homemade Apple",
  // --- SERIF (Elegant, Cinematic, Classic) ---
  "Merriweather",
  "Lora",
  "PT Serif",
  "Cormorant Garamond",
  "Tinos",
  "Libre Baskerville",
  "Domine",
  "EB Garamond",
  "Faustina",
  "Literata",
  "Source Serif 4",
  "Alegreya",
  "Caudex",
  "Gilda Display",
  "Uncial Antiqua",
  "Limelight",
  "Cinzel",
  // --- UNIQUE & FUN (Distincive Shapes) ---
  "Rubik Bubbles",
  "Metal Mania",
  "Creepster",
  "Nosifer",
  "Nosifier", // Added for redundancy
  "Rye",
  "Graduate",
  "Chonburi",
  "Fugaz One",
  "Unica One",
  "Krona One",
  "Megrim",
  "Stint Ultra Condensed",
  "Vidaloka",
  "Butcherman",
  "Mystery Quest",
  "Smokum",
  "Finger Paint",
  "Freckle Face",
  "Irish Grover",
];
