// src/lib/newCanvasPresets.ts
import { CanvasPreset } from "@/types/canvasPreset";

export const NEW_CANVAS_PRESETS: CanvasPreset[] = [
  {
    id: "graffiti-street-splash",
    name: "Graffiti Street Splash",
    styleTags: ["urban", "colorful", "modern", "bold"],
    background: {
      blankCanvasColor: "#1a1a1a",
      backgroundEffect: "none",
    },
    pip: {
      layoutMode: "pip",
      cameraShape: "circle",
      pipPosition: { x: 60, y: 35 },
      pipSize: { width: 35, height: 35 },
      pipBorder: { color: "#FF00FF", width: 5 },
      pipShadow: { blur: 30, color: "rgba(255, 0, 255, 0.6)" },
    },
    textOverlays: [
      {
        id: "graffiti-tag",
        content: "LIVE",
        style: {
          fontFamily: "Impact",
          fontSize: 120,
          color: "#00FF00",
          backgroundColor: "transparent",
          textShadow: "4px 4px 0px #FF00FF, 8px 8px 0px #00FFFF",
          fontWeight: "900",
          textAlign: "left",
        },
        layout: {
          position: { x: 5, y: 10 },
          size: { width: 45, height: 25 },
          zIndex: 20,
          rotation: -5,
          layerOrder: "above-video",
        },
      },
      {
        id: "spray-accent-1",
        content: "★",
        style: {
          fontFamily: "Arial",
          fontSize: 80,
          color: "#FFD700",
          backgroundColor: "transparent",
          textShadow: "0 0 20px #FFD700",
          textAlign: "center",
        },
        layout: {
          position: { x: 45, y: 8 },
          size: { width: 10, height: 10 },
          zIndex: 15,
          rotation: 15,
          layerOrder: "below-video",
        },
      },
      {
        id: "spray-accent-2",
        content: "◆",
        style: {
          fontFamily: "Arial",
          fontSize: 60,
          color: "#FF1493",
          backgroundColor: "transparent",
          textShadow: "0 0 15px #FF1493",
          textAlign: "center",
        },
        layout: {
          position: { x: 15, y: 75 },
          size: { width: 8, height: 8 },
          zIndex: 15,
          rotation: -20,
          layerOrder: "below-video",
        },
      },
    ],
    effects: {
      videoFilter: "saturate(1.2) contrast(1.1)",
    },
  },

  {
    id: "neon-cyberpunk-grid",
    name: "Neon Cyberpunk Grid",
    styleTags: ["tech", "modern", "neon", "futuristic"],
    background: {
      blankCanvasColor: "#0a0014",
      backgroundEffect: "none",
    },
    pip: {
      layoutMode: "pip",
      cameraShape: "hexagon",
      pipPosition: { x: 8, y: 25 },
      pipSize: { width: 40, height: 50 },
      pipBorder: { color: "#00FFFF", width: 4 },
      pipShadow: { blur: 40, color: "rgba(0, 255, 255, 0.8)" },
    },
    textOverlays: [
      {
        id: "cyber-title",
        content: "CYBER",
        style: {
          fontFamily: "Orbitron",
          fontSize: 64,
          color: "#00FFFF",
          backgroundColor: "transparent",
          textShadow: "0 0 30px #00FFFF, 0 0 60px #FF00FF",
          fontWeight: "700",
          textAlign: "center",
        },
        layout: {
          position: { x: 52, y: 15 },
          size: { width: 40, height: 12 },
          zIndex: 20,
          rotation: 0,
          layerOrder: "above-video",
        },
      },
      {
        id: "grid-line-1",
        content: "━━━━━━━━━━",
        style: {
          fontFamily: "Courier New",
          fontSize: 32,
          color: "#FF00FF",
          backgroundColor: "transparent",
          textShadow: "0 0 15px #FF00FF",
          textAlign: "center",
        },
        layout: {
          position: { x: 52, y: 30 },
          size: { width: 45, height: 5 },
          zIndex: 10,
          rotation: 0,
          layerOrder: "below-video",
        },
      },
      {
        id: "cyber-accent",
        content: "▲▲▲",
        style: {
          fontFamily: "Arial",
          fontSize: 48,
          color: "#FFD700",
          backgroundColor: "transparent",
          textShadow: "0 0 20px #FFD700",
          textAlign: "center",
        },
        layout: {
          position: { x: 54, y: 65 },
          size: { width: 15, height: 10 },
          zIndex: 15,
          rotation: 0,
          layerOrder: "above-video",
        },
      },
    ],
    effects: {
      videoFilter: "hue-rotate(20deg) saturate(1.4)",
      isNeonEdgeEnabled: true,
    },
  },

  {
    id: "retro-arcade-game",
    name: "Retro Arcade Game",
    styleTags: ["vintage", "colorful", "gaming", "retro"],
    background: {
      blankCanvasColor: "#1a0033",
      backgroundEffect: "none",
    },
    pip: {
      layoutMode: "pip",
      cameraShape: "rectangle",
      pipPosition: { x: 30, y: 45 },
      pipSize: { width: 40, height: 45 },
      pipBorder: { color: "#FFD700", width: 6 },
      pipShadow: { blur: 25, color: "rgba(255, 215, 0, 0.5)" },
    },
    textOverlays: [
      {
        id: "arcade-title",
        content: "PLAYER 1",
        style: {
          fontFamily: "Press Start 2P",
          fontSize: 36,
          color: "#00FF00",
          backgroundColor: "rgba(0, 0, 0, 0.7)",
          textShadow: "2px 2px 0px #FFFF00",
          fontWeight: "400",
          textAlign: "center",
        },
        layout: {
          position: { x: 25, y: 8 },
          size: { width: 50, height: 10 },
          zIndex: 20,
          rotation: 0,
          layerOrder: "above-video",
        },
      },
      {
        id: "pixel-heart-1",
        content: "♥♥♥",
        style: {
          fontFamily: "Arial",
          fontSize: 48,
          color: "#FF0055",
          backgroundColor: "transparent",
          textShadow: "0 0 15px #FF0055",
          textAlign: "center",
        },
        layout: {
          position: { x: 8, y: 12 },
          size: { width: 15, height: 8 },
          zIndex: 15,
          rotation: 0,
          layerOrder: "above-video",
        },
      },
      {
        id: "arcade-score",
        content: "9999",
        style: {
          fontFamily: "Press Start 2P",
          fontSize: 28,
          color: "#FFFF00",
          backgroundColor: "transparent",
          textShadow: "0 0 10px #FFFF00",
          textAlign: "center",
        },
        layout: {
          position: { x: 75, y: 10 },
          size: { width: 20, height: 6 },
          zIndex: 20,
          rotation: 0,
          layerOrder: "above-video",
        },
      },
      {
        id: "pixel-stars",
        content: "✦ ✦ ✦",
        style: {
          fontFamily: "Arial",
          fontSize: 56,
          color: "#00FFFF",
          backgroundColor: "transparent",
          textShadow: "0 0 20px #00FFFF",
          textAlign: "center",
        },
        layout: {
          position: { x: 15, y: 82 },
          size: { width: 70, height: 10 },
          zIndex: 10,
          rotation: 0,
          layerOrder: "below-video",
        },
      },
    ],
    effects: {
      videoFilter: "saturate(1.3) brightness(1.1)",
    },
  },

  {
    id: "comic-pop-art-boom",
    name: "Comic Pop Art BOOM",
    styleTags: ["colorful", "bold", "modern", "fun"],
    background: {
      blankCanvasColor: "#FFE600",
      backgroundEffect: "none",
    },
    pip: {
      layoutMode: "pip",
      cameraShape: "circle",
      pipPosition: { x: 50, y: 50 },
      pipSize: { width: 45, height: 45 },
      pipBorder: { color: "#000000", width: 8 },
      pipShadow: { blur: 0, color: "transparent" },
    },
    textOverlays: [
      {
        id: "comic-boom",
        content: "BOOM!",
        style: {
          fontFamily: "Impact",
          fontSize: 96,
          color: "#FF0000",
          backgroundColor: "transparent",
          textShadow: "4px 4px 0px #000000, -2px -2px 0px #FFFFFF",
          fontWeight: "900",
          textAlign: "center",
        },
        layout: {
          position: { x: 15, y: 8 },
          size: { width: 35, height: 18 },
          zIndex: 20,
          rotation: -8,
          layerOrder: "above-video",
        },
      },
      {
        id: "comic-stars-1",
        content: "★",
        style: {
          fontFamily: "Arial",
          fontSize: 72,
          color: "#0000FF",
          backgroundColor: "transparent",
          textShadow: "3px 3px 0px #000000",
          textAlign: "center",
        },
        layout: {
          position: { x: 8, y: 25 },
          size: { width: 8, height: 10 },
          zIndex: 15,
          rotation: 20,
          layerOrder: "below-video",
        },
      },
      {
        id: "comic-pow",
        content: "POW",
        style: {
          fontFamily: "Impact",
          fontSize: 56,
          color: "#00FF00",
          backgroundColor: "rgba(0, 0, 0, 0.8)",
          textShadow: "3px 3px 0px #000000",
          fontWeight: "900",
          textAlign: "center",
        },
        layout: {
          position: { x: 70, y: 75 },
          size: { width: 20, height: 12 },
          zIndex: 20,
          rotation: 15,
          layerOrder: "above-video",
        },
      },
      {
        id: "comic-dots",
        content: "• • • •",
        style: {
          fontFamily: "Arial",
          fontSize: 64,
          color: "#FF00FF",
          backgroundColor: "transparent",
          textAlign: "center",
        },
        layout: {
          position: { x: 58, y: 18 },
          size: { width: 30, height: 8 },
          zIndex: 10,
          rotation: 0,
          layerOrder: "below-video",
        },
      },
    ],
    effects: {
      videoFilter: "saturate(1.5) contrast(1.2)",
    },
  },

  {
    id: "abstract-geo-shapes",
    name: "Abstract Geometric",
    styleTags: ["modern", "minimal", "abstract", "artistic"],
    background: {
      blankCanvasColor: "#f0f0f0",
      backgroundEffect: "none",
    },
    pip: {
      layoutMode: "pip",
      cameraShape: "rectangle",
      pipPosition: { x: 55, y: 40 },
      pipSize: { width: 38, height: 50 },
      pipBorder: { color: "#FF6B6B", width: 0 },
      pipShadow: { blur: 30, color: "rgba(255, 107, 107, 0.3)" },
    },
    textOverlays: [
      {
        id: "geo-circle",
        content: "●",
        style: {
          fontFamily: "Arial",
          fontSize: 180,
          color: "#4ECDC4",
          backgroundColor: "transparent",
          textAlign: "center",
        },
        layout: {
          position: { x: 5, y: 15 },
          size: { width: 20, height: 25 },
          zIndex: 5,
          rotation: 0,
          layerOrder: "below-video",
        },
      },
      {
        id: "geo-square",
        content: "■",
        style: {
          fontFamily: "Arial",
          fontSize: 120,
          color: "#FFE66D",
          backgroundColor: "transparent",
          textAlign: "center",
        },
        layout: {
          position: { x: 15, y: 65 },
          size: { width: 15, height: 20 },
          zIndex: 5,
          rotation: 45,
          layerOrder: "below-video",
        },
      },
      {
        id: "geo-triangle",
        content: "▲",
        style: {
          fontFamily: "Arial",
          fontSize: 100,
          color: "#FF6B6B",
          backgroundColor: "transparent",
          textAlign: "center",
        },
        layout: {
          position: { x: 75, y: 10 },
          size: { width: 12, height: 15 },
          zIndex: 5,
          rotation: -15,
          layerOrder: "below-video",
        },
      },
      {
        id: "geo-line",
        content: "—",
        style: {
          fontFamily: "Arial",
          fontSize: 80,
          color: "#95E1D3",
          backgroundColor: "transparent",
          textAlign: "center",
        },
        layout: {
          position: { x: 70, y: 70 },
          size: { width: 25, height: 8 },
          zIndex: 10,
          rotation: 25,
          layerOrder: "above-video",
        },
      },
    ],
    effects: {
      videoFilter: "none",
    },
  },

  {
    id: "glitch-digital-matrix",
    name: "Glitch Digital Matrix",
    styleTags: ["tech", "modern", "digital", "cyberpunk"],
    background: {
      blankCanvasColor: "#000000",
      backgroundEffect: "none",
    },
    pip: {
      layoutMode: "pip",
      cameraShape: "rectangle",
      pipPosition: { x: 35, y: 30 },
      pipSize: { width: 30, height: 40 },
      pipBorder: { color: "#00FF00", width: 2 },
      pipShadow: { blur: 35, color: "rgba(0, 255, 0, 0.6)" },
    },
    textOverlays: [
      {
        id: "glitch-title",
        content: "GLITCH",
        style: {
          fontFamily: "Courier New",
          fontSize: 72,
          color: "#00FF00",
          backgroundColor: "transparent",
          textShadow: "2px 0px 0px #FF0000, -2px 0px 0px #00FFFF",
          fontWeight: "700",
          textAlign: "center",
        },
        layout: {
          position: { x: 8, y: 8 },
          size: { width: 35, height: 12 },
          zIndex: 20,
          rotation: -2,
          layerOrder: "above-video",
        },
      },
      {
        id: "matrix-code-1",
        content: "01010101",
        style: {
          fontFamily: "Courier New",
          fontSize: 24,
          color: "#00FF00",
          backgroundColor: "transparent",
          textShadow: "0 0 10px #00FF00",
          textAlign: "center",
        },
        layout: {
          position: { x: 68, y: 15 },
          size: { width: 25, height: 6 },
          zIndex: 10,
          rotation: 0,
          layerOrder: "below-video",
        },
      },
      {
        id: "matrix-code-2",
        content: "11001100",
        style: {
          fontFamily: "Courier New",
          fontSize: 24,
          color: "#00FF00",
          backgroundColor: "transparent",
          textShadow: "0 0 10px #00FF00",
          textAlign: "center",
        },
        layout: {
          position: { x: 70, y: 75 },
          size: { width: 25, height: 6 },
          zIndex: 10,
          rotation: 0,
          layerOrder: "below-video",
        },
      },
      {
        id: "glitch-bars",
        content: "▬▬▬",
        style: {
          fontFamily: "Arial",
          fontSize: 56,
          color: "#FF00FF",
          backgroundColor: "transparent",
          textShadow: "0 0 15px #FF00FF",
          textAlign: "center",
        },
        layout: {
          position: { x: 12, y: 65 },
          size: { width: 20, height: 10 },
          zIndex: 15,
          rotation: 0,
          layerOrder: "above-video",
        },
      },
    ],
    effects: {
      videoFilter: "hue-rotate(90deg) contrast(1.3)",
    },
  },

  {
    id: "spray-tag-urban",
    name: "Spray Tag Urban",
    styleTags: ["urban", "bold", "street", "graffiti"],
    background: {
      blankCanvasColor: "#2c2c2c",
      backgroundEffect: "none",
    },
    pip: {
      layoutMode: "pip",
      cameraShape: "circle",
      pipPosition: { x: 65, y: 55 },
      pipSize: { width: 32, height: 32 },
      pipBorder: { color: "#FF6B00", width: 6 },
      pipShadow: { blur: 40, color: "rgba(255, 107, 0, 0.7)" },
    },
    textOverlays: [
      {
        id: "spray-main",
        content: "FRESH",
        style: {
          fontFamily: "Impact",
          fontSize: 110,
          color: "#FF6B00",
          backgroundColor: "transparent",
          textShadow:
            "5px 5px 0px #000000, -2px -2px 0px #FFFFFF, 0 0 30px #FF6B00",
          fontWeight: "900",
          textAlign: "left",
        },
        layout: {
          position: { x: 8, y: 20 },
          size: { width: 50, height: 25 },
          zIndex: 20,
          rotation: -8,
          layerOrder: "above-video",
        },
      },
      {
        id: "spray-drip-1",
        content: "▼",
        style: {
          fontFamily: "Arial",
          fontSize: 48,
          color: "#00FFD1",
          backgroundColor: "transparent",
          textShadow: "0 0 15px #00FFD1",
          textAlign: "center",
        },
        layout: {
          position: { x: 15, y: 42 },
          size: { width: 5, height: 8 },
          zIndex: 15,
          rotation: 0,
          layerOrder: "below-video",
        },
      },
      {
        id: "spray-drip-2",
        content: "▼",
        style: {
          fontFamily: "Arial",
          fontSize: 48,
          color: "#FF00E6",
          backgroundColor: "transparent",
          textShadow: "0 0 15px #FF00E6",
          textAlign: "center",
        },
        layout: {
          position: { x: 45, y: 42 },
          size: { width: 5, height: 8 },
          zIndex: 15,
          rotation: 0,
          layerOrder: "below-video",
        },
      },
      {
        id: "spray-stars",
        content: "✦✦✦",
        style: {
          fontFamily: "Arial",
          fontSize: 64,
          color: "#FFD700",
          backgroundColor: "transparent",
          textShadow: "0 0 25px #FFD700",
          textAlign: "center",
        },
        layout: {
          position: { x: 10, y: 8 },
          size: { width: 35, height: 10 },
          zIndex: 10,
          rotation: 0,
          layerOrder: "below-video",
        },
      },
    ],
    effects: {
      videoFilter: "saturate(1.3) brightness(1.05)",
    },
  },

  {
    id: "pixel-art-retro",
    name: "Pixel Art Retro",
    styleTags: ["vintage", "gaming", "retro", "fun"],
    background: {
      blankCanvasColor: "#8B4789",
      backgroundEffect: "none",
    },
    pip: {
      layoutMode: "pip",
      cameraShape: "rectangle",
      pipPosition: { x: 10, y: 30 },
      pipSize: { width: 35, height: 40 },
      pipBorder: { color: "#FFD93D", width: 8 },
      pipShadow: { blur: 0, color: "transparent" },
    },
    textOverlays: [
      {
        id: "pixel-title",
        content: "8-BIT",
        style: {
          fontFamily: "Press Start 2P",
          fontSize: 48,
          color: "#FFD93D",
          backgroundColor: "rgba(0, 0, 0, 0.6)",
          textShadow: "3px 3px 0px #000000",
          fontWeight: "400",
          textAlign: "center",
        },
        layout: {
          position: { x: 50, y: 15 },
          size: { width: 45, height: 12 },
          zIndex: 20,
          rotation: 0,
          layerOrder: "above-video",
        },
      },
      {
        id: "pixel-heart",
        content: "♥",
        style: {
          fontFamily: "Arial",
          fontSize: 88,
          color: "#FF6B9D",
          backgroundColor: "transparent",
          textShadow: "4px 4px 0px #000000",
          textAlign: "center",
        },
        layout: {
          position: { x: 55, y: 65 },
          size: { width: 12, height: 12 },
          zIndex: 15,
          rotation: 0,
          layerOrder: "above-video",
        },
      },
      {
        id: "pixel-coin",
        content: "◉",
        style: {
          fontFamily: "Arial",
          fontSize: 72,
          color: "#FFD93D",
          backgroundColor: "transparent",
          textShadow: "3px 3px 0px #000000",
          textAlign: "center",
        },
        layout: {
          position: { x: 75, y: 68 },
          size: { width: 10, height: 10 },
          zIndex: 15,
          rotation: 0,
          layerOrder: "above-video",
        },
      },
      {
        id: "pixel-blocks",
        content: "█ █ █",
        style: {
          fontFamily: "Courier New",
          fontSize: 56,
          color: "#6BCB77",
          backgroundColor: "transparent",
          textAlign: "center",
        },
        layout: {
          position: { x: 52, y: 82 },
          size: { width: 40, height: 8 },
          zIndex: 10,
          rotation: 0,
          layerOrder: "below-video",
        },
      },
    ],
    effects: {
      videoFilter: "saturate(1.2)",
    },
  },

  {
    id: "stencil-street-art",
    name: "Stencil Street Art",
    styleTags: ["urban", "minimal", "street", "bold"],
    background: {
      blankCanvasColor: "#d4d4d4",
      backgroundEffect: "none",
    },
    pip: {
      layoutMode: "pip",
      cameraShape: "rectangle",
      pipPosition: { x: 52, y: 25 },
      pipSize: { width: 42, height: 55 },
      pipBorder: { color: "#000000", width: 5 },
      pipShadow: { blur: 20, color: "rgba(0, 0, 0, 0.5)" },
    },
    textOverlays: [
      {
        id: "stencil-text",
        content: "ART",
        style: {
          fontFamily: "Impact",
          fontSize: 140,
          color: "#000000",
          backgroundColor: "transparent",
          fontWeight: "900",
          textAlign: "center",
        },
        layout: {
          position: { x: 5, y: 30 },
          size: { width: 40, height: 30 },
          zIndex: 20,
          rotation: 0,
          layerOrder: "above-video",
        },
      },
      {
        id: "stencil-spray-1",
        content: "◊",
        style: {
          fontFamily: "Arial",
          fontSize: 96,
          color: "#FF0000",
          backgroundColor: "transparent",
          textAlign: "center",
        },
        layout: {
          position: { x: 8, y: 10 },
          size: { width: 12, height: 15 },
          zIndex: 10,
          rotation: 0,
          layerOrder: "below-video",
        },
      },
      {
        id: "stencil-spray-2",
        content: "◊",
        style: {
          fontFamily: "Arial",
          fontSize: 72,
          color: "#FF0000",
          backgroundColor: "transparent",
          textAlign: "center",
        },
        layout: {
          position: { x: 82, y: 75 },
          size: { width: 10, height: 12 },
          zIndex: 10,
          rotation: 0,
          layerOrder: "below-video",
        },
      },
      {
        id: "stencil-line",
        content: "━━━━━━━━",
        style: {
          fontFamily: "Courier New",
          fontSize: 28,
          color: "#000000",
          backgroundColor: "transparent",
          textAlign: "center",
        },
        layout: {
          position: { x: 8, y: 62 },
          size: { width: 35, height: 5 },
          zIndex: 15,
          rotation: 0,
          layerOrder: "above-video",
        },
      },
    ],
    effects: {
      videoFilter: "grayscale(0.3) contrast(1.3)",
    },
  },

  {
    id: "holographic-future",
    name: "Holographic Future",
    styleTags: ["tech", "modern", "luxury", "futuristic"],
    background: {
      blankCanvasColor: "#0d0221",
      backgroundEffect: "none",
    },
    pip: {
      layoutMode: "pip",
      cameraShape: "hexagon",
      pipPosition: { x: 30, y: 35 },
      pipSize: { width: 40, height: 50 },
      pipBorder: { color: "#B8F3FF", width: 3 },
      pipShadow: { blur: 50, color: "rgba(184, 243, 255, 0.8)" },
    },
    textOverlays: [
      {
        id: "holo-title",
        content: "FUTURE",
        style: {
          fontFamily: "Orbitron",
          fontSize: 68,
          color: "#B8F3FF",
          backgroundColor: "transparent",
          textShadow: "0 0 20px #B8F3FF, 0 0 40px #FF77FF, 0 0 60px #00D9FF",
          fontWeight: "700",
          textAlign: "center",
        },
        layout: {
          position: { x: 15, y: 8 },
          size: { width: 40, height: 12 },
          zIndex: 20,
          rotation: 0,
          layerOrder: "above-video",
        },
      },
      {
        id: "holo-ring",
        content: "○",
        style: {
          fontFamily: "Arial",
          fontSize: 200,
          color: "#FF77FF",
          backgroundColor: "transparent",
          textShadow: "0 0 40px #FF77FF",
          textAlign: "center",
        },
        layout: {
          position: { x: 55, y: 15 },
          size: { width: 35, height: 40 },
          zIndex: 5,
          rotation: 0,
          layerOrder: "below-video",
        },
      },
      {
        id: "holo-wave",
        content: "～～～～",
        style: {
          fontFamily: "Arial",
          fontSize: 64,
          color: "#00D9FF",
          backgroundColor: "transparent",
          textShadow: "0 0 20px #00D9FF",
          textAlign: "center",
        },
        layout: {
          position: { x: 18, y: 75 },
          size: { width: 40, height: 10 },
          zIndex: 10,
          rotation: 0,
          layerOrder: "below-video",
        },
      },
      {
        id: "holo-dots",
        content: "· · · · ·",
        style: {
          fontFamily: "Arial",
          fontSize: 48,
          color: "#FFB3FF",
          backgroundColor: "transparent",
          textShadow: "0 0 15px #FFB3FF",
          textAlign: "center",
        },
        layout: {
          position: { x: 65, y: 68 },
          size: { width: 30, height: 8 },
          zIndex: 15,
          rotation: 0,
          layerOrder: "above-video",
        },
      },
    ],
    effects: {
      videoFilter: "hue-rotate(180deg) saturate(1.5) brightness(1.1)",
      isNeonEdgeEnabled: true,
    },
  },

  {
    id: "newsroom-breaking",
    name: "Newsroom Breaking",
    styleTags: ["news", "professional", "broadcast", "modern"],
    background: {
      blankCanvasColor: "#0f172a",
      backgroundEffect: "none",
    },
    pip: {
      layoutMode: "pip",
      cameraShape: "rectangle",
      pipPosition: { x: 70, y: 25 },
      pipSize: { width: 35, height: 35 },
      pipBorder: { color: "#ffffff", width: 2 },
      pipShadow: { blur: 10, color: "rgba(0, 0, 0, 0.5)" },
    },
    textOverlays: [
      {
        id: "news-badge",
        content: "LIVE",
        style: {
          fontFamily: "Arial",
          fontSize: 24,
          color: "#ffffff",
          backgroundColor: "#dc2626",
          fontWeight: "700",
          textAlign: "center",
          padding: "4px 12px",
          borderRadius: "4px",
        },
        layout: {
          position: { x: 5, y: 5 },
          size: { width: 10, height: 6 },
          zIndex: 20,
          rotation: 0,
          layerOrder: "above-video",
        },
      },
      {
        id: "news-ticker-bg",
        content: "",
        style: {
          backgroundColor: "#ffffff",
        },
        layout: {
          position: { x: 0, y: 85 },
          size: { width: 100, height: 15 },
          zIndex: 10,
          rotation: 0,
          layerOrder: "above-video",
        },
      },
      {
        id: "news-headline",
        content: "BREAKING NEWS: TOP STORY",
        style: {
          fontFamily: "Arial",
          fontSize: 48,
          color: "#0f172a",
          fontWeight: "900",
          textAlign: "left",
          backgroundColor: "transparent",
        },
        layout: {
          position: { x: 5, y: 88 },
          size: { width: 90, height: 10 },
          zIndex: 20,
          rotation: 0,
          layerOrder: "above-video",
        },
      },
    ],
    effects: {
      videoFilter: "contrast(1.1)",
    },
  },

  {
    id: "coding-terminal",
    name: "Coding Terminal",
    styleTags: ["tech", "coding", "developer", "dark"],
    background: {
      blankCanvasColor: "#1e1e1e",
      backgroundEffect: "none",
    },
    pip: {
      layoutMode: "pip",
      cameraShape: "circle",
      pipPosition: { x: 85, y: 80 },
      pipSize: { width: 20, height: 20 },
      pipBorder: { color: "#4ade80", width: 2 },
      pipShadow: { blur: 0, color: "transparent" },
    },
    textOverlays: [
      {
        id: "term-cmd",
        content: "> npm run start:dev",
        style: {
          fontFamily: "Courier New",
          fontSize: 32,
          color: "#4ade80",
          backgroundColor: "transparent",
          textAlign: "left",
        },
        layout: {
          position: { x: 5, y: 10 },
          size: { width: 80, height: 8 },
          zIndex: 10,
          rotation: 0,
          layerOrder: "below-video",
        },
      },
      {
        id: "term-output",
        content: "Compiling...\nSuccess! (245ms)",
        style: {
          fontFamily: "Courier New",
          fontSize: 24,
          color: "#a3a3a3",
          backgroundColor: "transparent",
          textAlign: "left",
          whiteSpace: "pre-wrap",
        },
        layout: {
          position: { x: 5, y: 20 },
          size: { width: 80, height: 20 },
          zIndex: 10,
          rotation: 0,
          layerOrder: "below-video",
        },
      },
      {
        id: "term-cursor",
        content: "_",
        style: {
          fontFamily: "Courier New",
          fontSize: 32,
          color: "#4ade80",
          backgroundColor: "transparent",
          textAlign: "left",
        },
        layout: {
          position: { x: 5, y: 40 },
          size: { width: 5, height: 8 },
          zIndex: 10,
          rotation: 0,
          layerOrder: "below-video",
        },
      },
    ],
    effects: {
      videoFilter: "none",
    },
  },

  {
    id: "vintage-polaroid",
    name: "Vintage Polaroid",
    styleTags: ["vintage", "photo", "retro", "aesthetic"],
    background: {
      blankCanvasColor: "#fdfbf7",
      backgroundEffect: "none",
    },
    pip: {
      layoutMode: "pip",
      cameraShape: "rectangle",
      pipPosition: { x: 50, y: 45 },
      pipSize: { width: 50, height: 60 },
      pipBorder: { color: "#ffffff", width: 20 },
      pipShadow: { blur: 20, color: "rgba(0,0,0,0.15)" },
    },
    textOverlays: [
      {
        id: "polaroid-caption",
        content: "Summer Vibes ☀️",
        style: {
          fontFamily: "Brush Script MT",
          fontSize: 48,
          color: "#4a4a4a",
          backgroundColor: "transparent",
          textAlign: "center",
          fontWeight: "400",
        },
        layout: {
          position: { x: 50, y: 80 },
          size: { width: 40, height: 10 },
          zIndex: 20,
          rotation: -2,
          layerOrder: "above-video",
        },
      },
      {
        id: "polaroid-tape",
        content: "",
        style: {
          backgroundColor: "rgba(255, 255, 255, 0.4)",
          transform: "rotate(-45deg)",
        },
        layout: {
          position: { x: 25, y: 10 },
          size: { width: 15, height: 5 },
          zIndex: 25,
          rotation: -15,
          layerOrder: "above-video",
        },
      },
    ],
    effects: {
      videoFilter: "sepia(0.4) contrast(1.1) brightness(1.1)",
    },
  },

  {
    id: "esports-tournament",
    name: "Esports Tournament",
    styleTags: ["gaming", "esports", "competitive", "bold"],
    background: {
      blankCanvasColor: "#0b0029",
      backgroundEffect: "none",
    },
    pip: {
      layoutMode: "pip",
      cameraShape: "rectangle",
      pipPosition: { x: 50, y: 50 },
      pipSize: { width: 80, height: 60 },
      pipBorder: { color: "#7c3aed", width: 4 },
      pipShadow: { blur: 40, color: "#7c3aed" },
    },
    textOverlays: [
      {
        id: "esports-vs",
        content: "VS",
        style: {
          fontFamily: "Impact",
          fontSize: 120,
          color: "#ffffff",
          backgroundColor: "transparent",
          textShadow: "0 0 20px #7c3aed",
          fontWeight: "900",
          textAlign: "center",
        },
        layout: {
          position: { x: 50, y: 10 },
          size: { width: 20, height: 20 },
          zIndex: 20,
          rotation: 0,
          layerOrder: "above-video",
        },
      },
      {
        id: "esports-score-left",
        content: "3",
        style: {
          fontFamily: "Arial",
          fontSize: 80,
          color: "#3b82f6",
          backgroundColor: "transparent",
          fontWeight: "900",
          textAlign: "center",
        },
        layout: {
          position: { x: 20, y: 15 },
          size: { width: 10, height: 15 },
          zIndex: 20,
          rotation: 0,
          layerOrder: "above-video",
        },
      },
      {
        id: "esports-score-right",
        content: "2",
        style: {
          fontFamily: "Arial",
          fontSize: 80,
          color: "#ef4444",
          backgroundColor: "transparent",
          fontWeight: "900",
          textAlign: "center",
        },
        layout: {
          position: { x: 80, y: 15 },
          size: { width: 10, height: 15 },
          zIndex: 20,
          rotation: 0,
          layerOrder: "above-video",
        },
      },
    ],
    effects: {
      videoFilter: "saturate(1.2)",
      isNeonEdgeEnabled: true,
      neonColor: "#7c3aed",
    },
  },

  {
    id: "lofi-study",
    name: "Lofi Study Space",
    styleTags: ["chill", "lofi", "aesthetic", "calm"],
    background: {
      blankCanvasColor: "#e0e7ff",
      backgroundEffect: "none",
    },
    pip: {
      layoutMode: "pip",
      cameraShape: "rounded",
      pipPosition: { x: 75, y: 65 },
      pipSize: { width: 35, height: 45 },
      pipBorder: { color: "#ffffff", width: 8 },
      pipShadow: { blur: 20, color: "rgba(199, 210, 254, 0.8)" },
    },
    textOverlays: [
      {
        id: "lofi-title",
        content: "Study with me ☕",
        style: {
          fontFamily: "Arial",
          fontSize: 48,
          color: "#4338ca",
          backgroundColor: "transparent",
          fontWeight: "600",
          textAlign: "left",
        },
        layout: {
          position: { x: 10, y: 15 },
          size: { width: 50, height: 10 },
          zIndex: 10,
          rotation: 0,
          layerOrder: "below-video",
        },
      },
      {
        id: "lofi-time",
        content: "focus mode: on",
        style: {
          fontFamily: "Courier New",
          fontSize: 24,
          color: "#6366f1",
          backgroundColor: "#eef2ff",
          padding: "8px 16px",
          borderRadius: "20px",
          textAlign: "center",
        },
        layout: {
          position: { x: 10, y: 30 },
          size: { width: 30, height: 8 },
          zIndex: 10,
          rotation: 0,
          layerOrder: "below-video",
        },
      },
      {
        id: "lofi-decoration",
        content: "☁️",
        style: {
          fontFamily: "Arial",
          fontSize: 120,
          color: "#ffffff",
          backgroundColor: "transparent",
          textAlign: "center",
          opacity: 0.5,
        },
        layout: {
          position: { x: 20, y: 60 },
          size: { width: 20, height: 20 },
          zIndex: 5,
          rotation: 0,
          layerOrder: "below-video",
        },
      },
    ],
    effects: {
      videoFilter: "saturate(0.8) brightness(1.1)",
    },
  },

  {
    id: "modern-saas-demo",
    name: "Modern SaaS Demo",
    styleTags: ["business", "clean", "professional", "tech"],
    background: {
      blankCanvasColor: "#ffffff",
      backgroundEffect: "none",
    },
    pip: {
      layoutMode: "pip",
      cameraShape: "circle",
      pipPosition: { x: 15, y: 80 },
      pipSize: { width: 20, height: 20 },
      pipBorder: { color: "#2563eb", width: 4 },
      pipShadow: { blur: 15, color: "rgba(37, 99, 235, 0.2)" },
    },
    textOverlays: [
      {
        id: "saas-header",
        content: "New Features v2.0",
        style: {
          fontFamily: "Arial",
          fontSize: 64,
          color: "#1e293b",
          backgroundColor: "transparent",
          fontWeight: "800",
          textAlign: "center",
          letterSpacing: "-1px",
        },
        layout: {
          position: { x: 50, y: 40 },
          size: { width: 80, height: 12 },
          zIndex: 10,
          rotation: 0,
          layerOrder: "below-video",
        },
      },
      {
        id: "saas-subheader",
        content: "Simple. Fast. Reliable.",
        style: {
          fontFamily: "Arial",
          fontSize: 32,
          color: "#64748b",
          backgroundColor: "transparent",
          fontWeight: "500",
          textAlign: "center",
        },
        layout: {
          position: { x: 50, y: 55 },
          size: { width: 60, height: 8 },
          zIndex: 10,
          rotation: 0,
          layerOrder: "below-video",
        },
      },
      {
        id: "saas-accent",
        content: "",
        style: {
          backgroundColor: "#2563eb",
          borderRadius: "99px",
        },
        layout: {
          position: { x: 50, y: 30 },
          size: { width: 10, height: 1 },
          zIndex: 5,
          rotation: 0,
          layerOrder: "below-video",
        },
      },
    ],
    effects: {
      videoFilter: "none",
    },
  },

  {
    id: "spooky-horror",
    name: "Spooky Horror",
    styleTags: ["horror", "dark", "halloween", "scary"],
    background: {
      blankCanvasColor: "#1a0505",
      backgroundEffect: "none",
    },
    pip: {
      layoutMode: "pip",
      cameraShape: "rectangle",
      pipPosition: { x: 50, y: 50 },
      pipSize: { width: 60, height: 60 },
      pipBorder: { color: "#7f1d1d", width: 2 },
      pipShadow: { blur: 50, color: "#7f1d1d" },
    },
    textOverlays: [
      {
        id: "horror-text-top",
        content: "DON'T LOOK",
        style: {
          fontFamily: "Impact",
          fontSize: 80,
          color: "#991b1b",
          backgroundColor: "transparent",
          textShadow: "0 0 10px #000000",
          fontWeight: "700",
          textAlign: "center",
          letterSpacing: "5px",
        },
        layout: {
          position: { x: 50, y: 15 },
          size: { width: 80, height: 15 },
          zIndex: 20,
          rotation: 0,
          layerOrder: "above-video",
        },
      },
      {
        id: "horror-text-bottom",
        content: "BEHIND YOU",
        style: {
          fontFamily: "Impact",
          fontSize: 80,
          color: "#991b1b",
          backgroundColor: "transparent",
          textShadow: "0 0 10px #000000",
          fontWeight: "700",
          textAlign: "center",
          letterSpacing: "5px",
        },
        layout: {
          position: { x: 50, y: 85 },
          size: { width: 80, height: 15 },
          zIndex: 20,
          rotation: 0,
          layerOrder: "above-video",
        },
      },
    ],
    effects: {
      videoFilter: "grayscale(1) contrast(1.5) brightness(0.8)",
    },
  },

  {
    id: "cooking-lifestyle",
    name: "Cooking & Lifestyle",
    styleTags: ["food", "lifestyle", "cooking", "fresh"],
    background: {
      blankCanvasColor: "#fff7ed",
      backgroundEffect: "none",
    },
    pip: {
      layoutMode: "pip",
      cameraShape: "rectangle",
      pipPosition: { x: 30, y: 50 },
      pipSize: { width: 45, height: 80 },
      pipBorder: { color: "#fb923c", width: 0 },
      pipShadow: { blur: 20, color: "rgba(251, 146, 60, 0.3)" },
    },
    textOverlays: [
      {
        id: "cooking-title",
        content: "Fresh & Tasty",
        style: {
          fontFamily: "Georgia",
          fontSize: 56,
          color: "#c2410c",
          backgroundColor: "transparent",
          fontWeight: "700",
          textAlign: "left",
          fontStyle: "italic",
        },
        layout: {
          position: { x: 75, y: 20 },
          size: { width: 40, height: 15 },
          zIndex: 10,
          rotation: 0,
          layerOrder: "below-video",
        },
      },
      {
        id: "cooking-ingredients",
        content: "• Fresh Basil\n• Tomatoes\n• Olive Oil",
        style: {
          fontFamily: "Arial",
          fontSize: 24,
          color: "#431407",
          backgroundColor: "transparent",
          fontWeight: "400",
          textAlign: "left",
          lineHeight: 1.6,
          whiteSpace: "pre-wrap",
        },
        layout: {
          position: { x: 75, y: 45 },
          size: { width: 40, height: 30 },
          zIndex: 10,
          rotation: 0,
          layerOrder: "below-video",
        },
      },
      {
        id: "cooking-accent",
        content: "🌿",
        style: {
          fontFamily: "Arial",
          fontSize: 64,
          color: "#000000",
          backgroundColor: "transparent",
          textAlign: "center",
        },
        layout: {
          position: { x: 90, y: 85 },
          size: { width: 10, height: 10 },
          zIndex: 10,
          rotation: 15,
          layerOrder: "below-video",
        },
      },
    ],
    effects: {
      videoFilter: "saturate(1.1) brightness(1.05)",
    },
  },

  {
    id: "vaporwave-aesthetic",
    name: "Vaporwave Aesthetic",
    styleTags: ["vaporwave", "retro", "90s", "pink"],
    background: {
      blankCanvasColor: "#fbcfe8",
      backgroundEffect: "none",
    },
    pip: {
      layoutMode: "pip",
      cameraShape: "rectangle",
      pipPosition: { x: 50, y: 40 },
      pipSize: { width: 50, height: 50 },
      pipBorder: { color: "#00ffff", width: 4 },
      pipShadow: { blur: 0, color: "#ff00ff" },
    },
    textOverlays: [
      {
        id: "vapor-text",
        content: "A E S T H E T I C",
        style: {
          fontFamily: "Arial",
          fontSize: 40,
          color: "#ffffff",
          backgroundColor: "#000000",
          fontWeight: "700",
          textAlign: "center",
          letterSpacing: "8px",
        },
        layout: {
          position: { x: 50, y: 80 },
          size: { width: 90, height: 8 },
          zIndex: 20,
          rotation: 0,
          layerOrder: "above-video",
        },
      },
      {
        id: "vapor-sun",
        content: "",
        style: {
          background: "linear-gradient(to top, #ff00ff, #ff7700)",
          borderRadius: "50%",
        },
        layout: {
          position: { x: 50, y: 40 },
          size: { width: 30, height: 30 },
          zIndex: 5,
          rotation: 0,
          layerOrder: "below-video",
        },
      },
      {
        id: "vapor-grid-line",
        content: "____________________",
        style: {
          fontFamily: "Arial",
          fontSize: 40,
          color: "#00ffff",
          backgroundColor: "transparent",
          textAlign: "center",
          fontWeight: "bold",
        },
        layout: {
          position: { x: 50, y: 90 },
          size: { width: 100, height: 5 },
          zIndex: 15,
          rotation: 0,
          layerOrder: "below-video",
        },
      },
    ],
    effects: {
      videoFilter: "hue-rotate(-10deg) contrast(1.1)",
    },
  },

  {
    id: "fitness-energy",
    name: "Fitness Energy",
    styleTags: ["fitness", "workout", "gym", "energy"],
    background: {
      blankCanvasColor: "#ccfbf1",
      backgroundEffect: "none",
    },
    pip: {
      layoutMode: "pip",
      cameraShape: "rectangle",
      pipPosition: { x: 25, y: 50 },
      pipSize: { width: 40, height: 85 },
      pipBorder: { color: "#14b8a6", width: 8 },
      pipShadow: { blur: 0, color: "transparent" },
    },
    textOverlays: [
      {
        id: "fit-title",
        content: "HIIT BURN",
        style: {
          fontFamily: "Impact",
          fontSize: 96,
          color: "#14b8a6",
          backgroundColor: "transparent",
          fontWeight: "900",
          textAlign: "left",
          fontStyle: "italic",
        },
        layout: {
          position: { x: 75, y: 20 },
          size: { width: 45, height: 20 },
          zIndex: 10,
          rotation: -5,
          layerOrder: "below-video",
        },
      },
      {
        id: "fit-timer",
        content: "00:45",
        style: {
          fontFamily: "Courier New",
          fontSize: 64,
          color: "#0f766e",
          backgroundColor: "transparent",
          fontWeight: "700",
          textAlign: "center",
          border: "4px solid #0f766e",
          borderRadius: "10px",
          padding: "10px",
        },
        layout: {
          position: { x: 75, y: 60 },
          size: { width: 30, height: 15 },
          zIndex: 10,
          rotation: 0,
          layerOrder: "below-video",
        },
      },
    ],
    effects: {
      videoFilter: "contrast(1.2)",
    },
  },
];
